description: ''
handle: developers
name: Developers
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accessplugin-feed-me
  - accessplugin-navigation
  - accessplugin-retour
  - accessplugin-seomatic
  - accessplugin-webperf
  - accesssitewhensystemisoff
  - assignusergroups
  - assignuserpermissions
  - 'createentries:47b7409b-e345-48d9-b684-06ec0a2972f5' # FAQ
  - 'createentries:9de367ab-77b8-47bb-bbc3-63e79a202c3e' # News
  - 'createentries:a72bfe0c-3389-4f9f-8ec1-ab318ec10b29' # Errors
  - 'createentries:ef841ba4-7bcd-4ef5-9c12-96377bf7fba2' # Pages
  - 'createfoldersinvolume:1105c63e-3aaf-403a-8259-736f0a2d47f8' # Heroes
  - 'createfoldersinvolume:14e48735-7707-43d5-a6f1-90cc18da80f1' # Teasers
  - 'createfoldersinvolume:17ffd720-73f0-4e0c-9878-ea089fcc6863' # Sliders
  - 'createfoldersinvolume:2cfafcad-5b14-408b-ba81-afd942b8b3cb' # Profile Images
  - 'createfoldersinvolume:5c642d7e-b16b-4836-9575-668d75d242e5' # Branding
  - 'createfoldersinvolume:918b50e1-632c-4e92-a8c5-55eeb7b8571e' # Cover Photos
  - 'createfoldersinvolume:b011a3f9-88a2-4819-aad0-ca04487dfac8' # Documents
  - 'createfoldersinvolume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5' # Articles
  - customizesources
  - 'deleteentries:47b7409b-e345-48d9-b684-06ec0a2972f5' # FAQ
  - 'deleteentries:9de367ab-77b8-47bb-bbc3-63e79a202c3e' # News
  - 'deleteentries:a72bfe0c-3389-4f9f-8ec1-ab318ec10b29' # Errors
  - 'deleteentries:ef841ba4-7bcd-4ef5-9c12-96377bf7fba2' # Pages
  - 'deletefilesandfoldersinvolume:1105c63e-3aaf-403a-8259-736f0a2d47f8' # Heroes
  - 'deletefilesandfoldersinvolume:14e48735-7707-43d5-a6f1-90cc18da80f1' # Teasers
  - 'deletefilesandfoldersinvolume:17ffd720-73f0-4e0c-9878-ea089fcc6863' # Sliders
  - 'deletefilesandfoldersinvolume:2cfafcad-5b14-408b-ba81-afd942b8b3cb' # Profile Images
  - 'deletefilesandfoldersinvolume:5c642d7e-b16b-4836-9575-668d75d242e5' # Branding
  - 'deletefilesandfoldersinvolume:918b50e1-632c-4e92-a8c5-55eeb7b8571e' # Cover Photos
  - 'deletefilesandfoldersinvolume:b011a3f9-88a2-4819-aad0-ca04487dfac8' # Documents
  - 'deletefilesandfoldersinvolume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5' # Articles
  - 'deletepeerentries:47b7409b-e345-48d9-b684-06ec0a2972f5' # FAQ
  - 'deletepeerentries:9de367ab-77b8-47bb-bbc3-63e79a202c3e' # News
  - 'deletepeerentries:a72bfe0c-3389-4f9f-8ec1-ab318ec10b29' # Errors
  - 'deletepeerentries:ef841ba4-7bcd-4ef5-9c12-96377bf7fba2' # Pages
  - 'deletepeerentrydrafts:47b7409b-e345-48d9-b684-06ec0a2972f5' # FAQ
  - 'deletepeerentrydrafts:54e60257-f31a-44aa-960e-bbd364197e28' # Homepage
  - 'deletepeerentrydrafts:9de367ab-77b8-47bb-bbc3-63e79a202c3e' # News
  - 'deletepeerentrydrafts:a72bfe0c-3389-4f9f-8ec1-ab318ec10b29' # Errors
  - 'deletepeerentrydrafts:ef841ba4-7bcd-4ef5-9c12-96377bf7fba2' # Pages
  - 'deletepeerfilesinvolume:1105c63e-3aaf-403a-8259-736f0a2d47f8' # Heroes
  - 'deletepeerfilesinvolume:14e48735-7707-43d5-a6f1-90cc18da80f1' # Teasers
  - 'deletepeerfilesinvolume:17ffd720-73f0-4e0c-9878-ea089fcc6863' # Sliders
  - 'deletepeerfilesinvolume:2cfafcad-5b14-408b-ba81-afd942b8b3cb' # Profile Images
  - 'deletepeerfilesinvolume:5c642d7e-b16b-4836-9575-668d75d242e5' # Branding
  - 'deletepeerfilesinvolume:918b50e1-632c-4e92-a8c5-55eeb7b8571e' # Cover Photos
  - 'deletepeerfilesinvolume:b011a3f9-88a2-4819-aad0-ca04487dfac8' # Documents
  - 'deletepeerfilesinvolume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5' # Articles
  - deleteusers
  - 'editcategories:4e026396-d7ab-43ef-a817-226fb2dada30' # FAQ Categories
  - 'editcategories:f326369d-c220-40d9-92e9-7b7b7811d8e5' # News Categories
  - 'editentries:47b7409b-e345-48d9-b684-06ec0a2972f5' # FAQ
  - 'editentries:54e60257-f31a-44aa-960e-bbd364197e28' # Homepage
  - 'editentries:9de367ab-77b8-47bb-bbc3-63e79a202c3e' # News
  - 'editentries:a72bfe0c-3389-4f9f-8ec1-ab318ec10b29' # Errors
  - 'editentries:ef841ba4-7bcd-4ef5-9c12-96377bf7fba2' # Pages
  - 'editglobalset:64547f99-7471-496a-8b02-5d48e09a72f9' # Social Media
  - 'editglobalset:a2aa1ca5-9822-4918-9c36-9b612669921b' # Placeholders
  - 'editglobalset:dffe2f47-18b7-4dcb-845d-2d88fa0378c3' # Organisational Information
  - 'editimagesinvolume:1105c63e-3aaf-403a-8259-736f0a2d47f8' # Heroes
  - 'editimagesinvolume:14e48735-7707-43d5-a6f1-90cc18da80f1' # Teasers
  - 'editimagesinvolume:17ffd720-73f0-4e0c-9878-ea089fcc6863' # Sliders
  - 'editimagesinvolume:2cfafcad-5b14-408b-ba81-afd942b8b3cb' # Profile Images
  - 'editimagesinvolume:5c642d7e-b16b-4836-9575-668d75d242e5' # Branding
  - 'editimagesinvolume:918b50e1-632c-4e92-a8c5-55eeb7b8571e' # Cover Photos
  - 'editimagesinvolume:b011a3f9-88a2-4819-aad0-ca04487dfac8' # Documents
  - 'editimagesinvolume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5' # Articles
  - 'editpeerentries:47b7409b-e345-48d9-b684-06ec0a2972f5' # FAQ
  - 'editpeerentries:9de367ab-77b8-47bb-bbc3-63e79a202c3e' # News
  - 'editpeerentries:a72bfe0c-3389-4f9f-8ec1-ab318ec10b29' # Errors
  - 'editpeerentries:ef841ba4-7bcd-4ef5-9c12-96377bf7fba2' # Pages
  - 'editpeerentrydrafts:47b7409b-e345-48d9-b684-06ec0a2972f5' # FAQ
  - 'editpeerentrydrafts:54e60257-f31a-44aa-960e-bbd364197e28' # Homepage
  - 'editpeerentrydrafts:9de367ab-77b8-47bb-bbc3-63e79a202c3e' # News
  - 'editpeerentrydrafts:a72bfe0c-3389-4f9f-8ec1-ab318ec10b29' # Errors
  - 'editpeerentrydrafts:ef841ba4-7bcd-4ef5-9c12-96377bf7fba2' # Pages
  - 'editpeerfilesinvolume:1105c63e-3aaf-403a-8259-736f0a2d47f8' # Heroes
  - 'editpeerfilesinvolume:14e48735-7707-43d5-a6f1-90cc18da80f1' # Teasers
  - 'editpeerfilesinvolume:17ffd720-73f0-4e0c-9878-ea089fcc6863' # Sliders
  - 'editpeerfilesinvolume:2cfafcad-5b14-408b-ba81-afd942b8b3cb' # Profile Images
  - 'editpeerfilesinvolume:5c642d7e-b16b-4836-9575-668d75d242e5' # Branding
  - 'editpeerfilesinvolume:918b50e1-632c-4e92-a8c5-55eeb7b8571e' # Cover Photos
  - 'editpeerfilesinvolume:b011a3f9-88a2-4819-aad0-ca04487dfac8' # Documents
  - 'editpeerfilesinvolume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5' # Articles
  - 'editpeerimagesinvolume:1105c63e-3aaf-403a-8259-736f0a2d47f8' # Heroes
  - 'editpeerimagesinvolume:14e48735-7707-43d5-a6f1-90cc18da80f1' # Teasers
  - 'editpeerimagesinvolume:17ffd720-73f0-4e0c-9878-ea089fcc6863' # Sliders
  - 'editpeerimagesinvolume:2cfafcad-5b14-408b-ba81-afd942b8b3cb' # Profile Images
  - 'editpeerimagesinvolume:5c642d7e-b16b-4836-9575-668d75d242e5' # Branding
  - 'editpeerimagesinvolume:918b50e1-632c-4e92-a8c5-55eeb7b8571e' # Cover Photos
  - 'editpeerimagesinvolume:b011a3f9-88a2-4819-aad0-ca04487dfac8' # Documents
  - 'editpeerimagesinvolume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5' # Articles
  - editusers
  - impersonateusers
  - moderateusers
  - navigation-createnavs
  - 'navigation-deletenav:46faf86d-bfa5-4356-bef1-0af3b2a87332' # Secondary Navigation
  - 'navigation-deletenav:b51f4d5a-4d35-43f1-af05-72e206874892' # Footer Navigation
  - 'navigation-deletenav:d8cef538-a756-4496-b7f6-0e0bb61c14c2' # Primary Navigation
  - 'navigation-deletenav:e0745046-9bad-4922-8da8-7f677ba84909' # Legal Navigation
  - 'navigation-editnav:46faf86d-bfa5-4356-bef1-0af3b2a87332' # Secondary Navigation
  - 'navigation-editnav:b51f4d5a-4d35-43f1-af05-72e206874892' # Footer Navigation
  - 'navigation-editnav:d8cef538-a756-4496-b7f6-0e0bb61c14c2' # Primary Navigation
  - 'navigation-editnav:e0745046-9bad-4922-8da8-7f677ba84909' # Legal Navigation
  - 'navigation-managenav:46faf86d-bfa5-4356-bef1-0af3b2a87332' # Secondary Navigation
  - 'navigation-managenav:b51f4d5a-4d35-43f1-af05-72e206874892' # Footer Navigation
  - 'navigation-managenav:d8cef538-a756-4496-b7f6-0e0bb61c14c2' # Primary Navigation
  - 'navigation-managenav:e0745046-9bad-4922-8da8-7f677ba84909' # Legal Navigation
  - performupdates
  - 'publishentries:47b7409b-e345-48d9-b684-06ec0a2972f5' # FAQ
  - 'publishentries:54e60257-f31a-44aa-960e-bbd364197e28' # Homepage
  - 'publishentries:9de367ab-77b8-47bb-bbc3-63e79a202c3e' # News
  - 'publishentries:a72bfe0c-3389-4f9f-8ec1-ab318ec10b29' # Errors
  - 'publishentries:ef841ba4-7bcd-4ef5-9c12-96377bf7fba2' # Pages
  - 'publishpeerentries:47b7409b-e345-48d9-b684-06ec0a2972f5' # FAQ
  - 'publishpeerentries:9de367ab-77b8-47bb-bbc3-63e79a202c3e' # News
  - 'publishpeerentries:a72bfe0c-3389-4f9f-8ec1-ab318ec10b29' # Errors
  - 'publishpeerentries:ef841ba4-7bcd-4ef5-9c12-96377bf7fba2' # Pages
  - 'publishpeerentrydrafts:47b7409b-e345-48d9-b684-06ec0a2972f5' # FAQ
  - 'publishpeerentrydrafts:54e60257-f31a-44aa-960e-bbd364197e28' # Homepage
  - 'publishpeerentrydrafts:9de367ab-77b8-47bb-bbc3-63e79a202c3e' # News
  - 'publishpeerentrydrafts:a72bfe0c-3389-4f9f-8ec1-ab318ec10b29' # Errors
  - 'publishpeerentrydrafts:ef841ba4-7bcd-4ef5-9c12-96377bf7fba2' # Pages
  - registerusers
  - 'replacefilesinvolume:1105c63e-3aaf-403a-8259-736f0a2d47f8' # Heroes
  - 'replacefilesinvolume:14e48735-7707-43d5-a6f1-90cc18da80f1' # Teasers
  - 'replacefilesinvolume:17ffd720-73f0-4e0c-9878-ea089fcc6863' # Sliders
  - 'replacefilesinvolume:2cfafcad-5b14-408b-ba81-afd942b8b3cb' # Profile Images
  - 'replacefilesinvolume:5c642d7e-b16b-4836-9575-668d75d242e5' # Branding
  - 'replacefilesinvolume:918b50e1-632c-4e92-a8c5-55eeb7b8571e' # Cover Photos
  - 'replacefilesinvolume:b011a3f9-88a2-4819-aad0-ca04487dfac8' # Documents
  - 'replacefilesinvolume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5' # Articles
  - 'replacepeerfilesinvolume:1105c63e-3aaf-403a-8259-736f0a2d47f8' # Heroes
  - 'replacepeerfilesinvolume:14e48735-7707-43d5-a6f1-90cc18da80f1' # Teasers
  - 'replacepeerfilesinvolume:17ffd720-73f0-4e0c-9878-ea089fcc6863' # Sliders
  - 'replacepeerfilesinvolume:2cfafcad-5b14-408b-ba81-afd942b8b3cb' # Profile Images
  - 'replacepeerfilesinvolume:5c642d7e-b16b-4836-9575-668d75d242e5' # Branding
  - 'replacepeerfilesinvolume:918b50e1-632c-4e92-a8c5-55eeb7b8571e' # Cover Photos
  - 'replacepeerfilesinvolume:b011a3f9-88a2-4819-aad0-ca04487dfac8' # Documents
  - 'replacepeerfilesinvolume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5' # Articles
  - 'retour:dashboard'
  - 'retour:redirects'
  - 'retour:settings'
  - 'saveassetinvolume:1105c63e-3aaf-403a-8259-736f0a2d47f8' # Heroes
  - 'saveassetinvolume:14e48735-7707-43d5-a6f1-90cc18da80f1' # Teasers
  - 'saveassetinvolume:17ffd720-73f0-4e0c-9878-ea089fcc6863' # Sliders
  - 'saveassetinvolume:2cfafcad-5b14-408b-ba81-afd942b8b3cb' # Profile Images
  - 'saveassetinvolume:5c642d7e-b16b-4836-9575-668d75d242e5' # Branding
  - 'saveassetinvolume:918b50e1-632c-4e92-a8c5-55eeb7b8571e' # Cover Photos
  - 'saveassetinvolume:b011a3f9-88a2-4819-aad0-ca04487dfac8' # Documents
  - 'saveassetinvolume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5' # Articles
  - 'seomatic:content-meta'
  - 'seomatic:content-meta:facebook'
  - 'seomatic:content-meta:general'
  - 'seomatic:content-meta:sitemap'
  - 'seomatic:content-meta:twitter'
  - 'seomatic:dashboard'
  - 'seomatic:global-meta'
  - 'seomatic:global-meta:ads'
  - 'seomatic:global-meta:facebook'
  - 'seomatic:global-meta:general'
  - 'seomatic:global-meta:humans'
  - 'seomatic:global-meta:robots'
  - 'seomatic:global-meta:twitter'
  - 'seomatic:plugin-settings'
  - 'seomatic:site-settings'
  - 'seomatic:site-settings:creator'
  - 'seomatic:site-settings:identity'
  - 'seomatic:site-settings:miscellaneous'
  - 'seomatic:site-settings:sitemap'
  - 'seomatic:site-settings:social'
  - 'seomatic:tracking-scripts'
  - 'seomatic:tracking-scripts:facebookpixel'
  - 'seomatic:tracking-scripts:googleanalytics'
  - 'seomatic:tracking-scripts:googletagmanager'
  - 'seomatic:tracking-scripts:gtag'
  - 'seomatic:tracking-scripts:hubspot'
  - 'seomatic:tracking-scripts:linkedininsight'
  - 'utility:asset-indexes'
  - 'utility:clear-caches'
  - 'utility:db-backup'
  - 'utility:deprecation-errors'
  - 'utility:find-replace'
  - 'utility:migrations'
  - 'utility:php-info'
  - 'utility:queue-manager'
  - 'utility:system-messages'
  - 'utility:system-report'
  - 'utility:updates'
  - 'viewpeerfilesinvolume:1105c63e-3aaf-403a-8259-736f0a2d47f8' # Heroes
  - 'viewpeerfilesinvolume:14e48735-7707-43d5-a6f1-90cc18da80f1' # Teasers
  - 'viewpeerfilesinvolume:17ffd720-73f0-4e0c-9878-ea089fcc6863' # Sliders
  - 'viewpeerfilesinvolume:2cfafcad-5b14-408b-ba81-afd942b8b3cb' # Profile Images
  - 'viewpeerfilesinvolume:5c642d7e-b16b-4836-9575-668d75d242e5' # Branding
  - 'viewpeerfilesinvolume:918b50e1-632c-4e92-a8c5-55eeb7b8571e' # Cover Photos
  - 'viewpeerfilesinvolume:b011a3f9-88a2-4819-aad0-ca04487dfac8' # Documents
  - 'viewpeerfilesinvolume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5' # Articles
  - 'viewvolume:1105c63e-3aaf-403a-8259-736f0a2d47f8' # Heroes
  - 'viewvolume:14e48735-7707-43d5-a6f1-90cc18da80f1' # Teasers
  - 'viewvolume:17ffd720-73f0-4e0c-9878-ea089fcc6863' # Sliders
  - 'viewvolume:2cfafcad-5b14-408b-ba81-afd942b8b3cb' # Profile Images
  - 'viewvolume:5c642d7e-b16b-4836-9575-668d75d242e5' # Branding
  - 'viewvolume:918b50e1-632c-4e92-a8c5-55eeb7b8571e' # Cover Photos
  - 'viewvolume:b011a3f9-88a2-4819-aad0-ca04487dfac8' # Documents
  - 'viewvolume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5' # Articles
  - 'webperf:dashboard'
  - 'webperf:delete-data-samples'
  - 'webperf:delete-error-samples'
  - 'webperf:errors'
  - 'webperf:errors-detail'
  - 'webperf:performance'
  - 'webperf:performance-detail'
  - 'webperf:recommendations'
  - 'webperf:settings'
  - 'webperf:sidebar'
