fieldLayouts:
  8c95d207-c216-4f6a-b116-5592f7ade03b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: e7d483ec-b6b2-440d-8e97-ae6cc84d0adb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Optimized Images'
        sortOrder: 2
handle: heroes
hasUrls: true
name: Heroes
settings:
  addSubfolderToRootUrl: '1'
  autoFocalPoint: ''
  bucket: $S3_BUCKET
  bucketSelectionMode: manual
  cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
  cfPrefix: ''
  expires: '6 months'
  keyId: $S3_KEY_ID
  makeUploadsPublic: '1'
  region: $S3_REGION
  secret: $S3_SECRET
  storageClass: ''
  subfolder: heroes/
sortOrder: 8
type: craft\awss3\Volume
url: $CLOUDFRONT_URL
