field: e691301b-7484-40be-a3d4-c3bc590de959 # Content Builder
fieldLayouts:
  3041cc5a-1802-4565-802a-5b693e59e93f:
    tabs:
      -
        elements:
          -
            fieldUid: 3ef3485e-6187-4dac-af6b-66d630852b61 # Quote
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4133e37a-d625-476e-91aa-a600e0123064 # Quote Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 37051ce6-f0ea-4d54-97a5-e8c0f304f99c # Type
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3ef3485e-6187-4dac-af6b-66d630852b61: # Quote
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: 'Enter your quote.'
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4133e37a-d625-476e-91aa-a600e0123064: # Quote Source
    contentColumnType: string
    fieldGroup: null
    handle: quoteSource
    instructions: 'Select an entry or enter an external url to point to the source of the quote.'
    name: 'Quote Source'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  37051ce6-f0ea-4d54-97a5-e8c0f304f99c: # Type
    contentColumnType: string
    fieldGroup: null
    handle: quoteType
    instructions: 'Choose the type of quote.'
    name: Type
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Block Quote'
            -
              - value
              - blockQuote
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Pull Quote'
            -
              - value
              - pullQuote
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: blockQuote
name: Quotation
sortOrder: 4
