dateModified: 1639561075
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: $SENDER_NAME
  replyToEmail: $REPLY_TO
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0dd08fc1-c043-49cb-bdcf-80521b7bd98a: Settings # Settings
    1aad5a2f-f77c-42d8-8c02-c97817b9cb18: 'The Answer' # The Answer
    1c23eb9d-03fe-46ea-9bee-ff46e8bd15a3: 'Teaser Image' # Teaser Image
    1dd95078-7c8a-4ef7-8a16-e33a5341dadb: 'Image Optimisations ' # Image Optimisations 
    5da841b1-ca0d-46ff-8bb1-04d6c889ac54: Default # Default
    5ecf59f4-1339-4602-bd54-aa112f8f098e: Categories # Categories
    6a3feb81-50ce-467a-8aca-b5d4cc12aed0: Description # Description
    07a123c0-4e8e-4c19-a79e-61829f5d88c0: Builders # Builders
    11cffc84-a18e-49e3-9923-8229743b2a28: Branding # Branding
    35a1d959-d78e-4445-891c-7bb671c48281: 'Optimize Teasers' # Optimize Teasers
    54daa4d7-b5cf-4458-9e19-67155be19343: 'Organisation Phone' # Organisation Phone
    062e0067-ec18-423d-9e99-cce96beada4b: 'Optimize Covers' # Optimize Covers
    94b4d5ac-d7ea-4241-a6cb-92b39f482f99: Common # Common
    0314e405-e731-462f-9381-2cfb6ac91134: Images # Images
    451cb28a-2133-4681-977d-41c5a1cbc887: 'Full Logo' # Full Logo
    502c51a1-5b82-4368-90e1-aa68b1d4e479: 'Cover Photo' # Cover Photo
    634bebf5-ce96-4127-ab28-ee2541fb9f3b: 'Optimize Slider Images' # Optimize Slider Images
    648e7555-63ed-4228-a6b7-7811c865a7af: 'Category Description' # Category Description
    712cce4e-490d-44b8-bf2c-5d00c2de4c40: Assets # Assets
    0827c9dd-2ea2-4e98-b743-3161e028a304: 'FAQ Category' # FAQ Category
    870c07d7-9341-4f1f-825b-25c76239bc0d: Caption # Caption
    1266c39b-94f2-433c-ac8e-e84aa225a740: 'Header Builder' # Header Builder
    1572f461-2a67-47a4-a36c-80839168bcb7: Globals # Globals
    2473fef2-babd-4336-bb2e-550dc284282c: FAQ # FAQ
    6962a9b1-b802-4295-82b1-398470a9f54c: Author # Author
    9806bc10-174e-4280-b2a8-c684b99a3139: 'Optimize Profile Images' # Optimize Profile Images
    11916eb5-92ff-4945-bb06-1406d6047b36: 'Slider Image Placeholder' # Slider Image Placeholder
    64547f99-7471-496a-8b02-5d48e09a72f9: 'Social Media' # Social Media
    78023dfa-3c9e-47d1-bedc-b6fa76c9d751: 'Teaser Image Placeholder' # Teaser Image Placeholder
    97956e7f-3294-43b2-9d6a-e717706432bc: 'Optimize Articles' # Optimize Articles
    815594b4-d88f-4430-bf0c-5db890e1051f: 'Profile Photo' # Profile Photo
    6180741d-7a95-4c38-a6b8-13f0cd8dab1f: 'Logo Icon' # Logo Icon
    12311739-6ceb-4fb4-a572-7f2ea0ad3b69: Documents # Documents
    76099428-f3d4-42a7-9bb8-08f425b41461: 'Organisation Name' # Organisation Name
    a2aa1ca5-9822-4918-9c36-9b612669921b: Placeholders # Placeholders
    a5cb77be-c4d9-4d3e-88fb-d5384ca13941: 'Error Image' # Error Image
    a9df6c46-5d2c-4b29-96f7-4490417448b6: 'The Question' # The Question
    b8ba7115-3804-4c06-8a96-501963d1fc5c: 'Error Headline' # Error Headline
    b2330e68-6c4a-45ab-b5b1-8a510f75ce4f: General # General
    bbb59518-7cdc-4a7f-b07c-cd6b1fa8201d: Users # Users
    c014f72e-6101-4377-a9e4-bbea0f16bce8: Placeholders # Placeholders
    c157a704-5673-46ee-8e9b-49dfba9d3d5f: 'Hero Image Placeholder' # Hero Image Placeholder
    c439e251-a130-434d-a716-aab4d0651420: 'Navigation Settings' # Navigation Settings
    d08a0d16-0e00-49e6-9cd4-465fa2d65d7d: Errors # Errors
    d08d0466-34f4-441b-acd1-439b514f3810: 'Profile Photo Placeholder' # Profile Photo Placeholder
    d7c71eec-4319-4f22-8bc6-a8bf17da8f3d: 'News Categories' # News Categories
    d39b90d3-13a8-4d42-b415-1ef20426a174: 'Photo Cover Placeholder' # Photo Cover Placeholder
    dcdd5839-4bb5-4669-8d82-d46ec4da660a: 'Image Source' # Image Source
    df090dc9-1e25-4504-abd3-18e7996d8d6d: 'Article Image Placeholder' # Article Image Placeholder
    dffe2f47-18b7-4dcb-845d-2d88fa0378c3: 'Organisational Information' # Organisational Information
    e0ee7443-387e-4be3-a64f-3c5ae52be354: 'Organisation Email' # Organisation Email
    e6d658aa-c335-4f15-bbcd-59fe05d9e913: 'Error Text' # Error Text
    e7d483ec-b6b2-440d-8e97-ae6cc84d0adb: 'Optimize Heroes' # Optimize Heroes
    e691301b-7484-40be-a3d4-c3bc590de959: 'Content Builder' # Content Builder
    f89601e9-4ba9-4a48-9e99-350aa9914912: Default # Default
plugins:
  aws-s3:
    eager-beaver:
      enabled: true
      schemaVersion: 1.0.0
    enabled: true
    schemaVersion: '1.2'
  blitz-recommendations:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.2
  eager-beaver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  fastcgi-cache-bust:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    enabled: true
    schemaVersion: 4.4.0
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: false
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      createColorPalette: true
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - $SERVERLESS_SHARP_CLOUDFRONT_URL
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
                -
                  - includeBucketPrefix
                  - ''
      lowerQualityRetinaImageVariants: false
      transformClass: nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: VZHHXH5F4GCNNAD7EOB2O4AX
    schemaVersion: 1.0.21
    settings:
      bypassProjectConfig: false
      pluginName: Navigation
  notifications:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  password-policy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  position-fieldtype:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    enabled: true
    schemaVersion: 2.3.0
  retour:
    edition: standard
    enabled: true
    licenseKey: ZE62VWFIEPM6EVJRS53A9MHO
    schemaVersion: 3.0.9
    settings:
      additionalHeaders: ''
      alwaysStripQueryString: true
      automaticallyTrimStatistics: '1'
      createUriChangeRedirects: true
      dynamicRedirectDisplayLimit: 100
      enableApiEndpoint: ''
      excludePatterns: ''
      pluginName: Redirects
      preserveQueryString: false
      recordRemoteIp: true
      refreshIntervalSecs: 5
      staticRedirectDisplayLimit: 100
      statisticsRateLimitMs: '3600000'
      statsDisplayLimit: 1000
      statsStoredLimit: 1000
      stripQueryStringFromStats: true
      uriChangeRedirectSrcMatch: pathonly
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.11
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: ''
      enableMetaContainerEndpoint: ''
      environment: $ENVIRONMENT
      generatorEnabled: true
      headersEnabled: true
      lowercaseCanonicalUrl: '1'
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
        - linkedin
        - slack
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
  spoon:
    edition: standard
    enabled: true
    licenseKey: 5ORYCU819DCEOPQB8B5ERU5N
    schemaVersion: 3.5.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  timeloop:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  webperf:
    edition: standard
    enabled: true
    licenseKey: 6ZQLWJ6TZE7FF8BU5LXCVIGF
    schemaVersion: 1.0.1
  width-fieldtype:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: Craft
  schemaVersion: 3.7.8
  timeZone: Europe/London
